"""Offline tests for the ML surrogate training and evaluation pipeline.

The small dataset used here is generated by the existing dataset generator
with a fake NASA transport, so no test touches the network and no live NASA
data is required.  The thermal engine, NASA integration, and dataset generator
are exercised as dependencies; only the ML package behaviour is under test.
"""
import json
from datetime import datetime

import numpy as np
import pandas as pd
import pytest

from building_hvac_twin.ml import (
    FEATURE_COLUMNS,
    ML_TARGETS,
    build_models,
    grouped_design_split,
    prepare_features,
    regression_metrics,
    load_trained_models,
    save_model,
    train_models,
)
from building_hvac_twin.ml.dataset import (
    REQUIRED_DATASET_COLUMNS,
    load_dataset,
    validate_dataset,
)
from building_hvac_twin.ml.features import build_feature_row
from building_hvac_twin.shelter import DEFAULT_SCENARIOS
from building_hvac_twin.shelter.ml_dataset import generate_ml_dataset

# Synthetic test weather months for the fake transport.
_MONTH_BASE = {1: -10.0, 2: -8.0}
_MONTH_PEAK = {1: 450.0, 2: 520.0}


def _payload_for_date(nasa_date: str) -> dict:
    day = datetime.strptime(nasa_date, "%Y%m%d")
    temperatures, solar, wind, humidity = {}, {}, {}, {}
    for hour in range(24):
        key = f"{nasa_date}{hour:02d}"
        temperatures[key] = round(
            _MONTH_BASE[day.month] + 5.0 * np.sin(2.0 * np.pi * (hour - 8) / 24.0), 2
        )
        solar[key] = round(
            max(0.0, _MONTH_PEAK[day.month] * np.sin(np.pi * (hour - 7) / 12.0)), 1
        )
        wind[key] = 2.5
        humidity[key] = 41.0
    return {
        "properties": {
            "parameter": {
                "T2M": temperatures,
                "ALLSKY_SFC_SW_DWN": solar,
                "WS10M": wind,
                "RH2M": humidity,
            }
        }
    }


class FakeNasaTransport:
    def __call__(self, url: str, timeout_seconds: float) -> bytes:
        start = url.split("start=")[1].split("&")[0]
        return json.dumps(_payload_for_date(start)).encode()


@pytest.fixture(scope="module")
def ml_frame(tmp_path_factory) -> pd.DataFrame:
    cache_dir = tmp_path_factory.mktemp("ml_test_cache")
    result = generate_ml_dataset(
        design_count=10,
        seed=7,
        scenarios=list(DEFAULT_SCENARIOS[:2]),
        cache_dir=cache_dir,
        transport=FakeNasaTransport(),
        timeout_seconds=10.0,
    )
    return result.frame


@pytest.fixture(scope="module")
def ml_metadata(ml_frame) -> dict:
    return {
        "dataset_name": "shelter_ml_dataset",
        "seed": 7,
        "dataset": {"row_count": int(len(ml_frame))},
        "nasa_power": {
            "provenance_statement": (
                "NASA POWER data are satellite/reanalysis-derived estimates "
                "and are not ground measurements."
            ),
            # Test-only marker: this synthetic fixture asserts the loader's
            # live-retrieval guard, the same guard the real generated metadata
            # satisfies with retrieval_mode == "live".
            "retrieval_mode": "live",
        },
    }


@pytest.fixture(scope="module")
def ml_bundle(tmp_path_factory, ml_frame, ml_metadata):
    root = tmp_path_factory.mktemp("ml_bundle")
    csv_path = root / "shelter_ml_dataset.csv"
    meta_path = root / "shelter_ml_dataset_metadata.json"
    ml_frame.to_csv(csv_path, index=False)
    meta_path.write_text(json.dumps(ml_metadata, indent=2), encoding="utf-8")
    return load_dataset(csv_path, meta_path)


def test_dataset_loading_works(ml_bundle):
    assert ml_bundle.frame is not None
    assert len(ml_bundle.frame) == 20


def test_required_columns_present(ml_bundle):
    missing = [c for c in REQUIRED_DATASET_COLUMNS if c not in ml_bundle.frame.columns]
    assert not missing, missing


def test_expected_row_count(ml_bundle):
    assert len(ml_bundle.frame) == ml_bundle.metadata["dataset"]["row_count"] == 20


def test_no_required_nan(ml_bundle):
    assert not ml_bundle.frame[list(REQUIRED_DATASET_COLUMNS)].isna().any().any()


def test_load_fails_on_missing_file(tmp_path):
    with pytest.raises(FileNotFoundError):
        load_dataset(tmp_path / "missing.csv")


def test_load_fails_on_malformed_dataset(ml_bundle):
    bad = ml_bundle.frame.drop(columns=["window_u_value_w_m2k"])
    problems = validate_dataset(bad, ml_bundle.metadata)
    assert any("missing required columns" in problem for problem in problems)


def test_feature_preparation_is_deterministic(ml_frame):
    first = prepare_features(ml_frame)
    second = prepare_features(ml_frame)
    pd.testing.assert_frame_equal(first, second)
    assert list(first.columns) == list(FEATURE_COLUMNS)


def test_categorical_encoding_works(ml_frame):
    features = prepare_features(ml_frame)
    pipeline = build_models(seed=42, fast=True)["linear_regression"]
    y = ml_frame["mean_indoor_temperature_c"].astype(float)
    pipeline.fit(features, y)
    names = pipeline.named_steps["preprocessing"].get_feature_names_out()
    joined = " ".join(names)
    assert "wall_material_brick_masonry" in joined
    assert "window_wall_orientation" in joined


def test_grouped_split_prevents_design_leakage(ml_frame):
    split = grouped_design_split(ml_frame, seed=42)
    train_designs = set(ml_frame.iloc[split.train_index]["design_id"])
    valid_designs = set(ml_frame.iloc[split.validation_index]["design_id"])
    test_designs = set(ml_frame.iloc[split.test_index]["design_id"])
    assert not (train_designs & valid_designs)
    assert not (train_designs & test_designs)
    assert not (valid_designs & test_designs)
    assert len(test_designs) >= 1


def test_same_seed_produces_identical_splits(ml_frame):
    first = grouped_design_split(ml_frame, seed=7)
    second = grouped_design_split(ml_frame, seed=7)
    assert np.array_equal(first.train_index, second.train_index)
    assert np.array_equal(first.validation_index, second.validation_index)
    assert np.array_equal(first.test_index, second.test_index)


def test_models_train_successfully(ml_frame):
    features = prepare_features(ml_frame)
    y = ml_frame["mean_indoor_temperature_c"].astype(float)
    split = grouped_design_split(ml_frame, seed=42)
    fitted = train_models(
        lambda: build_models(seed=42, fast=True),
        features,
        {"mean_indoor_temperature_c": y},
        split.train_index,
        model_names=("linear_regression", "random_forest"),
    )
    assert set(fitted) == {
        ("mean_indoor_temperature_c", "linear_regression"),
        ("mean_indoor_temperature_c", "random_forest"),
    }


def test_predictions_have_correct_shape_and_finite(ml_frame):
    features = prepare_features(ml_frame)
    y = ml_frame["mean_indoor_temperature_c"].astype(float)
    split = grouped_design_split(ml_frame, seed=42)
    fitted = train_models(
        lambda: build_models(seed=42, fast=True),
        features,
        {"mean_indoor_temperature_c": y},
        split.train_index,
        model_names=("linear_regression",),
    )
    predicted = fitted[("mean_indoor_temperature_c", "linear_regression")].predict(features)
    assert predicted.shape == (len(ml_frame),)
    assert np.isfinite(predicted).all()


def test_evaluation_metrics_are_deterministic():
    y_true = np.array([1.0, 2.0, 3.0, 4.0])
    y_pred = np.array([1.1, 1.9, 3.2, 3.8])
    assert regression_metrics(y_true, y_pred) == regression_metrics(y_true, y_pred)


def test_performance_score_never_a_target():
    assert "performance_score" not in ML_TARGETS
    assert "performance_score" not in REQUIRED_DATASET_COLUMNS


def test_no_auxiliary_hvac_target_fabricated():
    for forbidden in ("auxiliary_heating_kwh", "auxiliary_cooling_kwh", "hvac_electricity_kwh"):
        assert forbidden not in ML_TARGETS


def test_saved_model_can_be_loaded_and_predict(tmp_path, ml_frame):
    features = prepare_features(ml_frame)
    y = ml_frame["mean_indoor_temperature_c"].astype(float)
    split = grouped_design_split(ml_frame, seed=42)
    fitted = train_models(
        lambda: build_models(seed=42, fast=True),
        features,
        {"mean_indoor_temperature_c": y},
        split.train_index,
        model_names=("random_forest",),
    )
    save_model(
        fitted[("mean_indoor_temperature_c", "random_forest")],
        tmp_path / "models",
        "mean_indoor_temperature_c",
        "random_forest",
    )
    loaded = load_trained_models(tmp_path / "models")
    assert ("mean_indoor_temperature_c", "random_forest") in loaded
    original = fitted[("mean_indoor_temperature_c", "random_forest")].predict(features)
    reloaded = loaded[("mean_indoor_temperature_c", "random_forest")].predict(features)
    np.testing.assert_allclose(original, reloaded)


def test_feature_ordering_consistent_between_train_and_predict(ml_frame):
    features = prepare_features(ml_frame)
    row = features.iloc[[0]]
    row_dict = {column: row[column].iloc[0] for column in FEATURE_COLUMNS}
    rebuilt = build_feature_row(row_dict, {})
    assert list(rebuilt.columns) == list(FEATURE_COLUMNS)
    # A trained model accepts the rebuilt single-row frame too.
    y = ml_frame["mean_indoor_temperature_c"].astype(float)
    split = grouped_design_split(ml_frame, seed=42)
    fitted = train_models(
        lambda: build_models(seed=42, fast=True),
        features,
        {"mean_indoor_temperature_c": y},
        split.train_index,
        model_names=("linear_regression",),
    )
    prediction = fitted[("mean_indoor_temperature_c", "linear_regression")].predict(rebuilt)
    assert prediction.shape == (1,)
    assert np.isfinite(prediction).all()