"""Surrogate ML layer on top of the passive shelter simulation dataset.

This package trains and evaluates reproducible regression models that learn
the mapping

    shelter design parameters + NASA POWER weather scenario features
        -> thermal simulation performance metrics

The models are trained on ``data/shelter_ml_dataset.csv``, whose targets were
generated by the existing thermal simulation engine (``simulate_shelter`` and
``design_metrics``) driven by NASA POWER satellite/reanalysis-derived weather.
Nothing here modifies the thermal engine, the NASA integration, or the dataset
generator; the ML layer only reads their outputs.

Provenance statements preserved from the dataset phase:

- NASA POWER data are satellite/reanalysis-derived estimates and are not
  ground measurements.
- ML targets are generated from the existing thermal simulation engine using
  NASA POWER satellite/reanalysis-derived weather inputs.  The models
  approximate simulation outputs under the represented NASA weather scenarios
  and design space; they do not predict measured building performance.
- ``performance_score`` is a relative cohort-dependent ranking metric and is
  never used as an ML target.
- The thermal engine is passive-only, so no auxiliary heating/cooling energy
  exists in the dataset and none is fabricated here.
"""
from .features import (
    CATEGORICAL_FEATURES,
    NUMERIC_FEATURES,
    FEATURE_COLUMNS,
    ML_TARGETS,
    prepare_features,
)
from .dataset import (
    DEFAULT_DATASET_PATH,
    DEFAULT_METADATA_PATH,
    MLBundle,
    load_dataset,
)
from .split import (
    DEFAULT_SPLIT_FRACTIONS,
    GroupedSplit,
    grouped_design_split,
)
from .models import (
    MODEL_NAMES,
    XGBOOST_AVAILABLE,
    build_models,
    model_library,
)
from .train import (
    MODEL_FILE_PATTERN,
    train_models,
    train_target,
    save_model,
)
from .evaluate import (
    regression_metrics,
    baseline_metrics,
    physical_sanity_report,
    feature_importance,
)
from .predict import (
    load_trained_models,
    predict_features,
    predict_design,
    load_dataset_row_features,
)

__all__ = [
    "CATEGORICAL_FEATURES",
    "NUMERIC_FEATURES",
    "FEATURE_COLUMNS",
    "ML_TARGETS",
    "prepare_features",
    "DEFAULT_DATASET_PATH",
    "DEFAULT_METADATA_PATH",
    "MLBundle",
    "load_dataset",
    "DEFAULT_SPLIT_FRACTIONS",
    "GroupedSplit",
    "grouped_design_split",
    "MODEL_NAMES",
    "XGBOOST_AVAILABLE",
    "build_models",
    "model_library",
    "MODEL_FILE_PATTERN",
    "train_models",
    "train_target",
    "save_model",
    "regression_metrics",
    "baseline_metrics",
    "physical_sanity_report",
    "feature_importance",
    "load_trained_models",
    "predict_features",
    "predict_design",
    "load_dataset_row_features",
]
